const moment = require('moment')
const ObjectId = id => id
const ISODate = ts => moment(ts, 'YYYY-MM-DDTHH:mm:ss.sssZ').toDate()

module.exports = {
    "_id" : ObjectId("613a6f60da1666c7dd21fbd0"),
    "user_id" : 1612197,
    "created" : ISODate("2022-04-29T04:51:19.118Z"),
    "service" : "nowhere",
    "origin_country_iso3" : "NLD",
    "delivery_info" : {
        "articles" : [],
        "articlesOpen" : [],
        "complete" : false,
        "upgrade" : false,
        "cashOnDelivery" : 0,
        "doorstepDelivery" : true,
        "branchDelivery" : false,
        "return" : false,
        "recipient" : "Brendan Biernat MD",
        "order_date" : ISODate("2022-04-29T09:51:19.118Z"),
        "street" : "977 Ireneusz Springs",
        "orderNo" : "Oa2l6Iuis",
        "customerNo" : "Bfx8K_f",
        "deliveryNo" : "ZlB6OAdiRm8F",
        "phone" : "56-884-81-50",
        "email" : "Nina.Kopczyski@parcellab.com",
        "city" : "Józefów (powiat biłgorajski)",
        "region" : "OM-DŚ",
        "language_iso3" : "pl",
        "announced_delivery_date" : ISODate("2022-05-02T04:51:19.118Z"),
        "timezone" : "Asia/Muscat"
    },
    "checkpoints" : [ 
        {
            "_id" : ObjectId("613a8d160cee83109d499ae0"),
            "courier" : "chronopost",
            "status_details" : "Shipment ready to be shipped",
            "event_timestamp" : ISODate("2022-04-29T02:26:21.118Z"),
            "status" : "DC",
            "country" : "Ukraina",
            "country_iso3" : "SWE",
            "city" : "Trzebiatów",
            "finger_print" : "Y1COq8lxzC2Fan26NByG27YyV6ObUao9",
            "created" : ISODate("2022-04-29T04:51:19.118Z")
        }, 
        {
            "_id" : ObjectId("613a8d160cee83109d499ae1"),
            "courier" : "chronopost",
            "status_details" : "Shipment picked up by driver",
            "event_timestamp" : ISODate("2022-04-29T06:08:48.118Z"),
            "status" : "PC",
            "country" : "Ukraina",
            "country_iso3" : "SWE",
            "city" : "Jarocin",
            "finger_print" : "CYqjuWhtLCi9lkgraqNU_3PPttxmsRJm",
            "created" : ISODate("2022-04-29T06:23:05.118Z")
        }, 
        {
            "_id" : ObjectId("613a8d160cee83109d499ae2"),
            "courier" : "chronopost",
            "status_details" : "Sorted at departure location / Comment: Sending supported by Chronopost, in transit",
            "event_timestamp" : ISODate("2022-04-29T06:46:35.118Z"),
            "status" : "SC",
            "country" : "Ukraina",
            "country_iso3" : "SWE",
            "city" : "Osiek",
            "finger_print" : "LUDnzTBgQtwZTaAkqnOXKlXglVu1ncVy",
            "created" : ISODate("2022-04-29T08:22:52.118Z")
        }, 
        {
            "_id" : ObjectId("613a8d160cee83109d499ae3"),
            "courier" : "chronopost",
            "status_details" : "Sorted at delivery location / Comment: Ready for shipment delivery",
            "event_timestamp" : ISODate("2022-04-29T19:19:33.118Z"),
            "status" : "SD",
            "country" : "Ukraina",
            "country_iso3" : "SWE",
            "city" : "Niemodlin",
            "finger_print" : "3wqq6mHeAMcbVlW9xOX9_5HVjnM96Y5K",
            "created" : ISODate("2022-04-29T20:25:06.118Z")
        }, 
        {
            "_id" : ObjectId("613a8d160cee83109d499ae4"),
            "courier" : "chronopost",
            "status_details" : "Shipment out for delivery",
            "event_timestamp" : ISODate("2022-04-29T19:25:35.118Z"),
            "status" : "TA",
            "country" : "Ukraina",
            "country_iso3" : "SWE",
            "city" : "Wałbrzych",
            "finger_print" : "1c1dsb24MQ1YK5AF2GuvwOasQmV6ouNU",
            "created" : ISODate("2022-04-29T21:55:08.118Z")
        }, 
        {
            "_id" : ObjectId("613a8d160cee83109d499ae5"),
            "courier" : "chronopost",
            "status_details" : "Delivery instruction received / Selected instruction: Safe place or additionnal information / new date: 03/05/2022",
            "event_timestamp" : ISODate("2022-04-30T00:55:21.118Z"),
            "status" : "CL",
            "country" : "Ukraina",
            "country_iso3" : "SWE",
            "city" : "Boguszów-Gorce",
            "finger_print" : "Eo61consat6DilpuriksWP9ASX3x2IQo",
            "created" : ISODate("2022-04-30T02:53:24.118Z")
        }, 
        {
            "_id" : ObjectId("613a8d160cee83109d499ae6"),
            "courier" : "chronopost",
            "status_details" : "Delivered / Comment: safe place",
            "event_timestamp" : ISODate("2022-04-30T00:56:07.118Z"),
            "status" : "D",
            "country" : "Ukraina",
            "country_iso3" : "SWE",
            "city" : "Lubniewice",
            "finger_print" : "tWvytYaLXZ3CHHn05aWmHvdR980HRs6v",
            "created" : ISODate("2022-04-30T02:53:24.118Z")
        }
    ],
    "securityHash" : "OCFKcr4kBA",
    "search_flag" : true,
    "need_prereporting" : true,
    "destination_country_iso3" : "AUT",
    "zip_code" : "10-137",
    "courier" : "chronopost",
    "tracking_number" : "PM98083429399606",
    "reporting" : {
        "invalid" : false,
        "forgotten" : false,
        "delayed" : false,
        "failedAttempt" : false,
        "dispatchDelayed" : false,
        "leadTimeExceeded" : false,
        "timeWindowMissed" : false,
        "escalated" : false,
        "returned" : false,
        "customerPromiseExceeded" : false,
        "contacted" : true,
        "contactedWithMessages" : [],
        "contactedAndBounce" : false,
        "exception_messages" : [],
        "lead_time" : 1,
        "lead_time_first_attempt" : 1,
        "lead_time_door_to_door" : 1,
        "lead_time_dispatch_delta" : -1,
        "lead_time_since_order" : 0,
        "lead_time_to_inbound" : 0,
        "pickup_date" : ISODate("2022-04-30T03:51:19.118Z"),
        "delivery_location" : "HomeDeposit"
    },
    "uniqueness" : "chronopost-PM98083429399606",
    "isTransport" : false,
    "recipient_id" : "5864c780276328776daff20a4302aa87cfc805193e6384bf9363900f04e0b82f"
}
