const moment = require('moment')
const ObjectId = id => id
const ISODate = ts => moment(ts, 'YYYY-MM-DDTHH:mm:ss.sssZ').toDate()

module.exports = {
    "_id" : ObjectId("613a6f75da1666c7dd21fdfa"),
    "user_id" : 1612197,
    "created" : ISODate("2022-05-01T11:09:08.804Z"),
    "service" : "nowhere",
    "origin_country_iso3" : "SWE",
    "delivery_info" : {
        "articles" : [],
        "articlesOpen" : [],
        "complete" : true,
        "upgrade" : false,
        "cashOnDelivery" : 0,
        "doorstepDelivery" : true,
        "branchDelivery" : false,
        "return" : true,
        "recipient" : "Willie Greenfelder",
        "order_date" : ISODate("2022-05-02T08:09:08.804Z"),
        "street" : "4345 O'Reilly Camp",
        "orderNo" : "JMcfIBI1p",
        "customerNo" : "skyr9ct",
        "deliveryNo" : "Z8HYPN0jutV1",
        "phone" : "055 7684 1761",
        "email" : "Ova.Gusikowski94@parcellab.com",
        "city" : "Des Moines",
        "region" : "NZ-TX",
        "language_iso3" : "en",
        "announced_delivery_date" : ISODate("2022-05-04T11:09:08.804Z"),
        "timezone" : "Pacific/Auckland"
    },
    "checkpoints" : [ 
        {
            "_id" : ObjectId("613a8d200cee83109d49ae25"),
            "courier" : "tnt",
            "status_details" : "Shipment in transit",
            "event_timestamp" : ISODate("2022-05-01T08:57:46.804Z"),
            "status" : "TUL",
            "country" : "Mayotte",
            "country_iso3" : "ESP",
            "city" : "Dayton",
            "finger_print" : "UyfYS4WSPNqI9D95sg9VrXw1QZc3JeKJ",
            "created" : ISODate("2022-05-01T11:09:08.804Z")
        }, 
        {
            "_id" : ObjectId("613a8d200cee83109d49ae26"),
            "courier" : "tnt",
            "status_details" : "Shipment is out for delivery.",
            "event_timestamp" : ISODate("2022-05-01T19:01:46.804Z"),
            "status" : "OD",
            "country" : "Mayotte",
            "country_iso3" : "ESP",
            "city" : "Worcester",
            "finger_print" : "lYHbxmi0lTNZw1AvEZ9XYo2B7Pt0ZY2w",
            "created" : ISODate("2022-05-01T20:09:50.804Z")
        }, 
        {
            "_id" : ObjectId("613a8d200cee83109d49ae27"),
            "courier" : "tnt",
            "status_details" : "Shipment delivered in good condition.",
            "event_timestamp" : ISODate("2022-05-01T22:41:46.804Z"),
            "status" : "RES",
            "country" : "Mayotte",
            "country_iso3" : "ESP",
            "city" : "St. Joseph",
            "finger_print" : "q7r1eeJUH1qHPbxkVWKTEuTa3MBc2nQ5",
            "created" : ISODate("2022-05-01T23:53:45.804Z")
        }
    ],
    "securityHash" : "RtUUFEA4LF",
    "search_flag" : true,
    "need_prereporting" : true,
    "destination_country_iso3" : "USA",
    "zip_code" : "IV56 2OM",
    "courier" : "tnt",
    "tracking_number" : "73776582777299",
    "reporting" : {
        "invalid" : false,
        "forgotten" : false,
        "delayed" : false,
        "failedAttempt" : false,
        "dispatchDelayed" : false,
        "leadTimeExceeded" : false,
        "timeWindowMissed" : false,
        "escalated" : false,
        "returned" : false,
        "customerPromiseExceeded" : false,
        "contacted" : true,
        "contactedWithMessages" : [],
        "contactedAndBounce" : false,
        "exception_messages" : [],
        "lead_time" : 1,
        "lead_time_first_attempt" : 1,
        "lead_time_door_to_door" : 1,
        "lead_time_dispatch_delta" : -1,
        "lead_time_since_order" : 0,
        "lead_time_to_inbound" : 0,
        "pickup_date" : ISODate("2022-05-02T16:09:08.804Z"),
        "delivery_location" : "Doorstep"
    },
    "uniqueness" : "tnt-73776582777299",
    "isTransport" : false,
    "recipient_id" : "96190fc44c0a0f8df27bb8fd7e3b0dbc08ed18dc1171e2f96fae277de76cf025"
}
